config/routes.rb
Rails.application.routes.draw do
  resources :yelp_grabs do
    collection do
      get "export_data"
      get 'search'
    end
  end

  require 'sidekiq/web'
  mount Sidekiq::Web, at: "/sidekiq"

  devise_for :users
  root 'home#index'
  resources :categories
  resources :posts, :sales_tools, :expshare_posts, :activity_posts, :globalfood_posts, :meetingrecord_posts, :evaluation_posts do
    collection do
      get 'by_tag/:tag', action: :by_tag, as: :by_tag
      get 'clear', action: :clear_search
      get 'by_username/:username', action: :by_username, as: :by_username, :constraints => { :username => /[^\/]+/ }
      get 'by_media_type/:media_type', action: :by_media_type, as: :by_media_type
      get 'by_category/:category', action: :by_category, as: :by_category
      get 'by_quick_search', action: :by_quick_search, as: :by_quick_search
      get 'by_complex_search', action: :by_complex_search, as: :by_complex_search
    end
  end
  resources :upload_files do
    post :create, on: :collection, :defaults => { :format => 'js' }
    get :download_file, on: :member
  end

  namespace :mine do
    resource :profile, controller: :profile
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @posts = Post.order('updated_at desc').limit(10)
  end
end

app/views/home/_menu.html.haml
= link_to I18n.t('board.sales_tools'), sales_tools_path, class: 'btn btn-primary'
= link_to I18n.t('board.experience_share'), expshare_posts_path, class: 'btn btn-primary'
= link_to I18n.t('board.activities'), activity_posts_path, class: 'btn btn-primary'
= link_to I18n.t('board.global_foods'), globalfood_posts_path, class: 'btn btn-primary'
= link_to I18n.t('board.meeting_records'), meetingrecord_posts_path, class: 'btn btn-primary'
= link_to I18n.t('board.evaluations'), evaluation_posts_path, class: 'btn btn-primary'

.align-right
  = link_to t("board.search_tools"), by_complex_search_sales_tools_path, class: 'btn btn-primary'

app/views/home/index.html.haml
%h1 Sales Assistant System
= render 'menu'

#posts_list
  = render partial: 'posts/posts_list', :posts => @posts