config/routes.rb
Rails.application.routes.draw do
  resources :yelp_grabs do
    collection do
      get "export_data"
      get 'search'
    end
  end

  require 'sidekiq/web'
  mount Sidekiq::Web, at: "/sidekiq"

  devise_for :users
  root 'home#index'
  resources :categories
  resources :posts, :sales_tools, :expshare_posts, :activity_posts, :globalfood_posts, :meetingrecord_posts, :evaluation_posts do
    collection do
      get 'by_tag/:tag', action: :by_tag, as: :by_tag
      get 'clear', action: :clear_search
      get 'by_username/:username', action: :by_username, as: :by_username, :constraints => { :username => /[^\/]+/ }
      get 'by_media_type/:media_type', action: :by_media_type, as: :by_media_type
      get 'by_category/:category', action: :by_category, as: :by_category
      get 'by_quick_search', action: :by_quick_search, as: :by_quick_search
      get 'by_complex_search', action: :by_complex_search, as: :by_complex_search
    end
  end
  resources :upload_files do
    post :create, on: :collection, :defaults => { :format => 'js' }
    get :download_file, on: :member
  end

  namespace :mine do
    resource :profile, controller: :profile
  end
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :category
  belongs_to :user
  has_many :upload_files, dependent: :destroy
  validates :user, :title, presence: true

  acts_as_taggable
  MediaType = %w(中文大紀元 英文大紀元 新唐人 雜誌 網站 亞洲美食 其他)

  scope :by_quick_search, ->(query) { joins(:upload_files).where('title like :query OR content like :query OR upload_files.image like :query', query: "%#{query}%") }

  self.per_page = 20

  def author
    user.username || user.email
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:edit, :update, :destroy, :show]
  before_action :check_authorization
  before_action :set_categories, only: [:index, :create, :by_category, :by_complex_search, :new, :edit]

  def index
    if params[:post_search]
      @post_search = PostSearch.new(post_search_params, controller_name)
      @posts = @post_search.search
    else
      @post_search = PostSearch.new
      @posts = model_name.order('updated_at desc')
    end
    @posts ||= model_name.none
    @posts = @posts.page(params[:page])
  end

  def clear_search
    current_user.tmp_params={}
    current_user.save
    redirect_to  :action => "index"
  end

  def show
  end

  def new
    @post = model_name.new
    @tag = @post.tags.build
  end

  def create
    @post = model_name.new(post_params.merge(user: current_user))
    params[:upload_file_ids].try(:each) {|id| @post.upload_files << UploadFile.try(:find, id)}

    if @post.save
      flash[:notice] = 'Post Success'
      redirect_to action: 'index'
    else
      flash[:error] = @post.errors.full_messages.join(', ')
      render 'index'
    end
  end

  def edit
    @tags = @post.tags
  end

  def update
    if @post.update(post_params)
      params[:upload_file_ids].try(:each) {|id| @post.upload_files << UploadFile.try(:find, id)}
      flash[:notice] = 'Update Success'
      redirect_to action: 'index'
    else
      flash[:error] = @post.errors.full_messages.join(', ')
      render 'index'
    end
  end

  def destroy
    @post.destroy
    flash[:notice] = 'Delete Success'
    redirect_to action: :index
  end

  def by_tag
    if params[:tag] == 'all'
      @posts = model_name.order('updated_at desc').page(params[:page])
    else
      @posts = model_name.tagged_with(params[:tag]).order('updated_at desc').page(params[:page])
    end
  end

  def by_username
    if params[:username] == 'all'
      @posts = model_name.order('updated_at desc').page(params[:page])
    else
      user = User.find_by_email(params[:username])
      @posts = user.posts.order('updated_at desc').page(params[:page]) if user
    end
  end

  def by_media_type
    if params[:media_type] == 'all'
      @posts = model_name.order('updated_at desc').page(params[:page])
    else
      @posts = model_name.where(media_type: params[:media_type]).order('updated_at desc').page(params[:page])
    end
  end

  def by_category
    if params[:category] == 'all'
      @posts = model_name.order('updated_at desc').page(params[:page])
    else
      @posts = model_name.joins(:category).where(categories: {name: params[:category]} ).order('updated_at desc').page(params[:page])
    end
  end

  def by_quick_search
   if params[:query]
     @posts = model_name.by_quick_search(params[:query]).order('updated_at desc')
   end
    @posts ||= model_name.none
    @posts = @posts.page(params[:page])
  end

  def by_complex_search
    if params[:post_search]
      @post_search = PostSearch.new(post_search_params, controller_name)
      @posts = @post_search.search
    else
      @post_search = PostSearch.new
    end
    @posts ||= model_name.none
    @posts = @posts.page(params[:page])
  end

  private

  def set_categories
    @categories = Category.all
  end

  def check_authorization
    raise 'authorization unaccessed' if controller_name == 'posts' and action_name != 'by_quick_search'
  end

  def model_name
    controller_name.classify.constantize
  end

  helper_method :model_name

  def set_post
    @post = model_name.find(params[:id])
  end

  def post_params
    params.require(controller_name.singularize).permit(:title, :content, :tag_list, :category_id)
  end

  def post_search_params
    set_params
    params.require(:post_search).permit(:title, :content, :media_type, :tag, :category_id, :user_id)
  end

  def set_params
    params[:post_search] = current_user.tmp_params.merge!(params[:post_search])
    current_user.tmp_params = params[:post_search]
    current_user.save    
  end
end

app/helpers/posts_helper.rb
module PostsHelper
  def file_icon(file)
    if file.try(:image).try(:content_type).try(:include?, 'image')
      image_tag file.try(:image).try(:thumb).try(:url)
    else
      image_tag file.try(:image).try(:default_url)
    end
  end

  def current_controller
    controller.controller_name
  end

  def is_current_controller_sales_tool?
    controller.controller_name == "sales_tools"
  end
end

app/views/posts/_menu.html.haml
= link_to 'Home', root_path, class: 'btn btn-default'
= link_to I18n.t('board.sales_tools'), sales_tools_path, class: 'btn btn-default'
= link_to I18n.t('board.experience_share'), expshare_posts_path, class: 'btn btn-default'
= link_to I18n.t('board.activities'), activity_posts_path, class: 'btn btn-default'
= link_to I18n.t('board.global_foods'), globalfood_posts_path, class: 'btn btn-default'
= link_to I18n.t('board.meeting_records'), meetingrecord_posts_path, class: 'btn btn-default'
= link_to I18n.t('board.evaluations'), evaluation_posts_path, class: 'btn btn-default'

app/views/posts/_post.html.haml
%table.table.table-hover
  %thead
    %tr
      %th Title 
      %th Content
      %th Category
      %th Author
      %th Updated Time
      %th Media Type
      %th Tags
  - @posts.each_with_index do |post,i|  
    %tbody
      %tr  
        %td= post.title
        %td= post.content
        - if post.category
          %td= link_to post.category.try(:name), polymorphic_path([:by_category, post.class], category: post.category.try(:name) || '')
        %td= link_to post.author, polymorphic_path([:by_username, post.class], username: post.user.try(:email))
        %td= post.updated_at
        %td= link_to post.media_type, polymorphic_path([:by_media_type, post.class], media_type: post.media_type || '')
        %td= raw post.tag_list.map{|t| link_to t, polymorphic_path([:by_tag, post.class], tag: t)}.join(', ')

app/views/posts/_posts_list.html.haml
%table.table.table-hover.post-list
  %thead
    %tr
      %th= t('table.title')
      %th= t('table.content')
      %th= t('table.category')
      %th= t('table.author')
      %th= t('table.updated_time')
      - if is_current_controller_sales_tool?
        %th= t('table.media_type')
      %th= t('table.tags')
      %th
      %th
  - @posts.each_with_index do |post,i|
    %tbody
      %tr
        %td{title: post.title}= link_to "#{truncate(post.title, length: 20)}", polymorphic_path(post)
        %td{title: post.content}= truncate(post.content, length: 20)
        - if post.category
          %td= link_to post.category.try(:name), polymorphic_path([:by_category, post.class], category: post.category.try(:name) || '')
        - else
          %td
        %td= link_to post.author, polymorphic_path([:by_username, post.class], username: post.user.try(:email))
        %td.time-tag= post.updated_at.strftime("%R %D")
        - if is_current_controller_sales_tool?
          %td= link_to post.media_type, polymorphic_path([:by_media_type, post.class], media_type: post.media_type || '')
        %td= raw post.tag_list.map{|t| link_to t, polymorphic_path([:by_tag, post.class], tag: t)}.join(', ')
        - if post.user.try(:email) == current_user.email || current_user.admin?
          .btn-group
            %td= link_to I18n.t('button.edit'), edit_polymorphic_path(post), class: "btn btn-warning btn-xs"
            %td= link_to I18n.t('button.destroy'), polymorphic_path(post), method: :delete, class: "btn btn-danger btn-xs"
        - else
          %td= link_to I18n.t('button.edit'), edit_polymorphic_path(post), class: "btn btn-warning btn-xs", disabled: "disabled"
          %td= link_to I18n.t('button.destroy'), polymorphic_path(post), method: :delete, class: "btn btn-danger btn-xs", disabled: "disabled"


app/views/posts/_search_links_head.html.haml
.row.normal-row
  = link_to t("board.category_search"), polymorphic_path([:by_category, controller.controller_name], category: 'all'), class: 'btn btn-warning'
  = link_to t("board.tags_search"), polymorphic_path([:by_tag, controller.controller_name], tag: 'all'), class: 'btn btn-warning'
  = link_to t("board.user_search"), polymorphic_path([:by_username, controller.controller_name], username: 'all'), class: 'btn btn-warning'
  - if is_current_controller_sales_tool?
    = link_to t("board.media_type_search"), polymorphic_path([:by_media_type, controller.controller_name], media_type: 'all'), class: 'btn btn-warning'
  = link_to t("board.complex_search"), polymorphic_path([:by_complex_search, controller.controller_name]), class: 'btn btn-warning'

app/views/posts/_sidebar.html.haml
%ul.nav.nav-sidebar
  = link_to t("board.clear_search"), polymorphic_path([:clear, controller.controller_name]), class: "btn btn-warning btn-sm"
  %h4
    %b= t("board.user")
  .option-group
    - User.all.each do |user|
      %li
      - if current_user.tmp_params[:user_id].to_i == user.id 
        = link_to user.username || user.email, polymorphic_path(current_controller, 'post_search[user_id]' => user.id ), class: "active"
      - else
        = link_to user.username || user.email, polymorphic_path(current_controller, 'post_search[user_id]' => user.id )
  - if current_controller == "sales_tools_controller"
    %h4
      %b= t("board.media_type")
    .option-group
      - Post::MediaType.each do |type|
        %li
        - if current_user.tmp_params[:media_type] == type 
          = link_to type, polymorphic_path(current_controller, 'post_search[media_type]' => type ), class: "active" 
        - else
          = link_to type, polymorphic_path(current_controller, 'post_search[media_type]' => type )
  %h4
    %b= t("board.tags")
  .option-group
    %li
      - model_name.tag_counts.each do |tag|
        = content_tag :span do
          - if current_user.tmp_params[:tag] == tag.name
            = link_to tag.name, polymorphic_path(current_controller, 'post_search[tag]' => tag.name), class: "active"
          - else
            = link_to tag.name, polymorphic_path(current_controller, 'post_search[tag]' => tag.name)

app/views/posts/_upload_files.html.haml
%ul.list-group
  - upload_files.try(:each) do |file|
    %li.list-group-item
      = file_icon(file)
      = file.try(:image).try(:file).try(:filename)
      = link_to 'Download', download_file_upload_file_path(file), class: "btn btn-primary"

app/views/posts/by_category.html.haml
.row
  = render 'menu'
.row
  .col-md-offset-5
    %h3
      Category Search Page
.row
  .col-md-6
    = render 'search_links_head'
.row
  Categories
  - @categories.pluck(:name).each do |c|
    = link_to c, polymorphic_path([:by_category, controller.controller_name], category: c), class: 'btn btn-default'

#posts_list
  = render partial: 'posts_list', :posts => @posts
= will_paginate @posts

app/views/posts/by_complex_search.html.haml
.row
  = render 'menu'
.row
  .col-md-offset-5
    %h3
      Complex Search
.row
  .col-md-6
    = render 'search_links_head'
.row
  = simple_form_for @post_search, url: polymorphic_path([:by_complex_search, controller.controller_name]), method: :get, html: {class: 'form-inline'} do |f|
    = f.input_field :title, placeholder: t("board.title"), class: 'form-control'
    = f.input_field :category_id, collection: @categories, include_blank: t("board.select_category"), class: 'form-control'
    - if is_current_controller_sales_tool?
      = f.input_field :media_type, collection: Post::MediaType, prompt: t("board.select_media_type"), class: 'form-control'
    = f.input_field :tag, placeholder: t("board.tags"), class: 'form-control'
    = f.input_field :user_id, collection: User.all, label_method: :email, value_method: :id, include_blank: t("board.select_user"), class: 'form-control'
    = f.button :submit, t("board.new_search")

#posts_list
  = render partial: 'posts_list', :posts => @posts
= will_paginate @posts

app/views/posts/by_media_type.html.haml
.row
  = render 'menu'
.row
  .col-md-offset-5
    %h3
      Media Type Search Page
.row
  .col-md-6
    = render 'search_links_head'
.row
  Media Types
  - Post::MediaType.each do |mt|
    = link_to mt, polymorphic_path([:by_media_type, controller.controller_name], media_type: mt), class: 'btn btn-default'

#posts_list
  = render partial: 'posts_list', :posts => @posts
= will_paginate @posts

app/views/posts/by_quick_search.html.haml
.row
  = render 'menu'
.row
  .col-md-offset-5
    %h3
      Search Page

#posts_list
  = render partial: 'posts_list', :posts => @posts
= will_paginate @posts

app/views/posts/by_tag.html.haml
.row
  = render 'menu'
.row
  .col-md-offset-5
    %h3
      Tag Search Page
.row
  .col-md-6
    = render 'search_links_head'
.row
  Tags
  - tag_cloud Post.tag_counts, %w{s m l} do |tag, css_class|
    = link_to tag.name, polymorphic_path([:by_tag, controller.controller_name], tag: tag.name), class: 'btn btn-default'

#posts_list
  = render partial: 'posts_list', :posts => @posts
= will_paginate @posts

app/views/posts/edit.html.haml
.row
  .col-md-offset-4
    %h3= t('board.edit') + ' ' + @post.title

= render 'post_form'

app/views/posts/new.html.haml
%h1.col-md-offset-4= t("board.create_post")
= render 'post_form'

app/views/posts/show.html.haml
.jumbotron.row
  .col-md-8.col-md-offset-2
    %h1.col-md-offset-4
      = @post.title
    %ul.list-group.post-show
      - if @post.category.present?
        %li.list-group-item
          .row
            .col-md-2
              %span.label.label-info=t("board.category")
            .col-md-6
              = @post.category.try(:name)
      %li.list-group-item
        .row
          .col-md-2
            %span.label.label-info=t("board.content")
          .col-md-8
            = @post.content
      %li.list-group-item
        .row
          .col-md-2
            %span.label.label-info=t("board.tags")
          .col-md-6
            = @post.tag_list
      - if @post.media_type.present?
        %li.list-group-item
          .row
            .col-md-2
              %span.label.label-info=t("board.media_type")
            .col-md-6
              = @post.media_type
      %li.list-group-item
        .row
          .col-md-2
            .label.label-info=t("board.updated_at")
          .col-md-6
            = @post.updated_at.strftime('%m-%d-%Y %I:%M %P')
      %li.list-group-item
        .row
          .col-md-2
            %span.label.label-info=t("board.author_name")
          .col-md-6
            = @post.user.try(:username) || @post.user.try(:email)
      %li.list-group-item
        .row
          .col-md-2
            %span.label.label-info=t("board.files")
          .col-md-6
            = render partial: 'posts/upload_files', locals: { upload_files: @post.upload_files }