config/routes.rb
Rails.application.routes.draw do
  resources :yelp_grabs do
    collection do
      get "export_data"
      get 'search'
    end
  end

  require 'sidekiq/web'
  mount Sidekiq::Web, at: "/sidekiq"

  devise_for :users
  root 'home#index'
  resources :categories
  resources :posts, :sales_tools, :expshare_posts, :activity_posts, :globalfood_posts, :meetingrecord_posts, :evaluation_posts do
    collection do
      get 'by_tag/:tag', action: :by_tag, as: :by_tag
      get 'clear', action: :clear_search
      get 'by_username/:username', action: :by_username, as: :by_username, :constraints => { :username => /[^\/]+/ }
      get 'by_media_type/:media_type', action: :by_media_type, as: :by_media_type
      get 'by_category/:category', action: :by_category, as: :by_category
      get 'by_quick_search', action: :by_quick_search, as: :by_quick_search
      get 'by_complex_search', action: :by_complex_search, as: :by_complex_search
    end
  end
  resources :upload_files do
    post :create, on: :collection, :defaults => { :format => 'js' }
    get :download_file, on: :member
  end

  namespace :mine do
    resource :profile, controller: :profile
  end
end

app/models/yelp_grab.rb
#require_relative '../../lib/yelp'
class YelpGrab < ActiveRecord::Base
  include CsvParse
  include ExportCsv
  include Scraper::YelpScraper

  belongs_to :user

  validates_presence_of :name, :address
  validates_uniqueness_of :name, :address

  self.per_page = 20

  scope :text_search, ->(attr, value){ where("lower(#{attr}) like ?", "%#{value.downcase}%") }

  def self.csv_import path
    csv_parse(path).each do |params|
      yp = find_or_initialize_by(address: params["address"])
      yp.update!(params)
    end
  end

  def self.genres
    pluck(:genre).compact.uniq.reject!(&:blank?)
  end

  def self.boroughs
    pluck(:borough).compact.uniq
  end

  def self.zipcodes
    pluck(:zipcode).compact.uniq.reject!(&:blank?).sort
  end

  def self.cities
    pluck(:city).compact.uniq.reject!(&:blank?)
  end

  def self.grab_all
    yelp_urls = [
           {
            url: "http://www.yelp.com/search?find_desc=&find_loc=ny&ns=1&cflt=restaurants&l=p:NY:New_York:Manhattan:Theater_District",
            borough: "Manhattan",
            primary_industry: "restaurant"
           },
           {
            url: "http://www.yelp.com/search?find_desc=&find_loc=ny&ns=1&cflt=restaurants&l=p:NY:New_York:Manhattan:Upper_East_Side",
            borough: "Manhattan",
            primary_industry: "restaurant"
           },
           {
            url: "http://www.yelp.com/search?find_desc=&find_loc=ny&ns=1&cflt=restaurants&l=p:NY:New_York:Manhattan:[Upper_West_Side,Washington_Heights]",
            borough: "Manhattan",
            primary_industry: "restaurant"
           },
           {
            url: "http://www.yelp.com/search?find_desc=&find_loc=ny&ns=1&cflt=restaurants&l=p:NY:New_York:Brooklyn:Bay_Ridge",
            borough: "Brooklyn",
            primary_industry: "restaurant"
           },
           {
            url: "http://www.yelp.com/search?find_desc=&find_loc=ny&ns=1&cflt=restaurants&l=p:NY:New_York:Manhattan:West_Village",
            borough: "Manhattan",
            primary_industry: "restaurant"
           },
           {
            url: "http://www.yelp.com/search?find_desc=&find_loc=ny&ns=1&cflt=restaurants&l=p:NY:New_York:Brooklyn:[Bath_Beach,Bergen_Beach,Boerum_Hill]",
            borough: "Brooklyn",
            primary_industry: "restaurant"
           },
           {
            url: "http://www.yelp.com/search?find_desc=&find_loc=ny&ns=1&cflt=restaurants&l=p:NY:New_York:Manhattan:Yorkville",
            borough: "Manhattan",
            primary_industry: "restaurant"
           },
           {
            url: "http://www.yelp.com/search?find_desc=&find_loc=ny&ns=1&cflt=restaurants&l=p:NY:New_York:Brooklyn:[Bedford_Stuyvesant,Bensonhurst]",
            borough: "Brooklyn",
            primary_industry: "restaurant"
           },
           {
            url: "http://www.yelp.com/search?find_desc=&find_loc=ny&ns=1&cflt=restaurants&l=p:NY:New_York:Brooklyn:[Borough_Park,Brighton_Beach,Brooklyn_Heights,Brownsville,Canarsie,Carroll_Gardens,City_Line]",
            borough: "Brooklyn",
            primary_industry: "restaurant"
           },
           {
            url: "http://www.yelp.com/search?find_desc=&find_loc=ny&ns=1&cflt=restaurants&l=p:NY:New_York:Brooklyn:[Bushwick,Clinton_Hill,Cobble_Hill,Columbia_Street_Waterfront_District,Coney_Island]",
            borough: "Brooklyn",
            primary_industry: "restaurant"
           },
    ]


    yelp_urls.each do |yelp_url|
      browser_grab(yelp_url[:url], borough: yelp_url[:borough], primary_industry: yelp_url[:primary_industry])
    end
  end

  def rating
    self[:rating] && self[:rating][/\d+\.\d+/]
  end

  def username
    user && user.username || "unassigned"
  end

  def url
    self[:url] && "https://www.yelp.com" + self[:url]
  end
end

app/controllers/yelp_grabs_controller.rb
class YelpGrabsController < ApplicationController
  before_action :set_yelp, only: [:edit, :update]

  def index
    @yelps = YelpGrab.order(updated_at: :desc).page(params[:page])
    @yelpdata_search = YelpdataSearch.new
  end

  def export_data
    YelpGrab.export
    send_file(Rails.root.join('public', 'yelp.csv'))
  end

  def search
    @yelpdata_search = YelpdataSearch.new(yelpdata_search_params)
    @yelps = @yelpdata_search.results.order(updated_at: :desc).page(params[:page])
    render :index
  end

  def edit
   
  end

  def new
    @yelp = YelpGrab.new
  end

  def create
    @yelp = YelpGrab.new(yelp_params)

    if @yelp.save
      flash[:notice] = t "yelp.created_success"
      redirect_to action: :index
    else
      flash[:alert] = t "yelp.created_failed"
      render :edit
    end
  end

  def update
    if @yelp.update(yelp_params)
      flash[:notice] = t "yelp.updated_success"
      redirect_to action: :index
    else
      flash[:alert] = t "yelp.updated_failed"
      render :edit
    end
  end

  private

  def set_yelp
    @yelp = YelpGrab.find params[:id]
  end

  def yelpdata_search_params
    params.require(:yelpdata_search).permit(:name, :genre, :address, :borough, :zipcode, :city, :user_id)
  end

  def yelp_params
    params.require(:yelp_grab).permit(:name, :address, :phone_num, :yelp_id, :city, :zipcode, :street, :genre,
                                      :rating, :account_name, :description, :revenue, :employees, :ownership,
                                      :primary_industry, :state, :country, :lead_source, :parent_name, :address_remark,
                                      :remark, :borough, :user_id)
  end
end

app/views/yelp_grabs/_form.html.haml
.jumbotron
  .container
    = simple_form_for @yelp, html: {class: "form-horizontal"} do |f|
      = render "shared/form_error_messages", object: @yelp

      .form-group
        %label.control-label.col-md-2= t("yelp.assign_to")
        .col-md-7
          = f.input_field :user_id, collection: User.all, value_method: :id, label_method: :username, prompt: "Select a sales man", class: 'form-control'
      .form-group
        %label.control-label.col-md-2= t("yelp.remark")
        .col-md-7
          = f.input_field :remark, class: 'form-control'
      .form-group
        %label.control-label.col-md-2= t("yelp.name")
        .col-md-7
          = f.input_field :name, class: 'form-control'
      .form-group
        %label.control-label.col-md-2= t("yelp.genre")
        .col-md-7
          = f.input_field :genre, class: 'form-control'
      .form-group
        %label.control-label.col-md-2= t("yelp.rating")
        .col-md-7
          = f.input_field :rating, class: 'form-control'
      .form-group
        %label.control-label.col-md-2= t("yelp.phone_number")
        .col-md-7
          = f.input_field :phone_num, class: 'form-control'
      .form-group
        %label.control-label.col-md-2= t("yelp.address")
        .col-md-7
          = f.input_field :address, class: 'form-control'
      .form-group
        %label.control-label.col-md-2= t("yelp.city")
        .col-md-7
          = f.input_field :city, class: 'form-control'
      .form-group
        %label.control-label.col-md-2= t("yelp.borough")
        .col-md-7
          = f.input_field :borough, class: 'form-control'
      .form-group
        %label.control-label.col-md-2= t("yelp.zipcode")
        .col-md-7
          = f.input_field :zipcode, class: 'form-control'
      .form-group
        %label.control-label.col-md-2 Yelp Url
        .col-md-7
          = f.input_field :url, class: 'form-control', readonly: true
      .form-group
        %label.control-label.col-md-2= t("yelp.description")
        .col-md-7
          = f.input_field :description, class: 'form-control'
      .form-group
        %label.control-label.col-md-2= t("yelp.revenue")
        .col-md-7
          = f.input_field :revenue, class: 'form-control'
      .form-group
        %label.control-label.col-md-2= t("yelp.employees")
        .col-md-7
          = f.input_field :employees, class: 'form-control'
      .form-group
        %label.control-label.col-md-2= t("yelp.ownership")
        .col-md-7
          = f.input_field :ownership, class: 'form-control'
      .form-group
        %label.control-label.col-md-2= t("yelp.primary_industry")
        .col-md-7
          = f.input_field :primary_industry, class: 'form-control'
      .form-group
        %label.control-label.col-md-2= t("yelp.parent_name")
        .col-md-7
          = f.input_field :parent_name, class: 'form-control'
      .form-group
        %label.control-label.col-md-2= t("yelp.lead_source")
        .col-md-7
          = f.input_field :lead_source, class: 'form-control'
      .form-group
        .col-md-offset-2
          = f.button :submit, 'Submit', class: "btn btn-default"

app/views/yelp_grabs/_searchbar.html.haml
= simple_form_for @yelpdata_search, url: search_yelp_grabs_path, method: :get, html: {class: 'form-inline'} do |f|
  .row.inline-row
    = f.input_field :name, placeholder: t('yelp.name'), class: 'form-control'
    = f.input_field :genre, placeholder: t('yelp.select_genre'), class: 'form-control'
    = f.input_field :user_id, collection: User.all, value_method: :id, label_method: :username, prompt: t('yelp.select_user'), class: 'form-control'
  .row.inline-row
    = f.input_field :address, placeholder: t('yelp.address'), class: 'form-control'
    = f.input_field :borough, collection: YelpGrab.boroughs, prompt: t('yelp.select_borough'), class: 'form-control'
    = f.input_field :zipcode, collection: YelpGrab.zipcodes, prompt: t('yelp.select_zipcode'), class: 'form-control'
    = f.input_field :city, placeholder: t('yelp.select_city'), class: 'form-control'
    = f.submit t('yelp.search'), class: 'btn btn-primary'
    = link_to t('yelp.clear'), yelp_grabs_path, class: 'btn btn-default'

app/views/yelp_grabs/edit.html.haml
%h3.col-md-offset-4= t "yelp.edit" + " " + @yelp.name

= render 'form'

app/views/yelp_grabs/index.html.haml
= link_to "Export Csv", export_data_yelp_grabs_path, class: "btn btn-primary"
= link_to "New", new_yelp_grab_path, class: "btn btn-primary"

= render "searchbar"

%table.table.table-hover
  %thead
    %tr
      %th= t 'yelp.name'
      %th= t 'yelp.assign_to'
      %th= t 'yelp.remark'
      %th= t 'yelp.genre'
      %th= t 'yelp.rating'
      %th= t 'yelp.phone_number'
      %th= t 'yelp.address'
      %th= t 'yelp.date'
      %th= t 'yelp.city'
      %th= t 'yelp.borough'
      %th= t 'yelp.zipcode'
      %th
  - @yelps.each_with_index do |y, i|
    %tbody
      %tr
        %td
          = link_to y.url, target: "_blank" do
            %span{title: y.name}= truncate(y.name, length: 20)
        %td= y.username
        %td{title: y.remark}= truncate(y.remark, length: 10)
        %td{title: y.genre}= truncate(y.genre, length: 10)
        %td= y.rating
        %td= y.phone_num
        %td{title: y.address}= truncate(y.address, length: 10)
        %td= y.updated_at.strftime('%b/%d/%Y')
        %td{title: y.city}= truncate(y.city, length: 10)
        %td= y.borough
        %td= y.zipcode
        - if current_user == y.user || current_user.admin?
          %td= link_to t('yelp.edit'), edit_yelp_grab_path(y), class: 'btn btn-warning btn-xs'
        - else
          %td= link_to t('yelp.edit'), edit_yelp_grab_path(y), class: 'btn btn-warning btn-xs', disabled: true

= will_paginate @yelps

app/views/yelp_grabs/new.html.haml
%h3.col-md-offset-4= t "yelp.new"

= render 'form'