config/routes.rb
Rails.application.routes.draw do
  resources :yelp_grabs do
    collection do
      get "export_data"
      get 'search'
    end
  end

  require 'sidekiq/web'
  mount Sidekiq::Web, at: "/sidekiq"

  devise_for :users
  root 'home#index'
  resources :categories
  resources :posts, :sales_tools, :expshare_posts, :activity_posts, :globalfood_posts, :meetingrecord_posts, :evaluation_posts do
    collection do
      get 'by_tag/:tag', action: :by_tag, as: :by_tag
      get 'clear', action: :clear_search
      get 'by_username/:username', action: :by_username, as: :by_username, :constraints => { :username => /[^\/]+/ }
      get 'by_media_type/:media_type', action: :by_media_type, as: :by_media_type
      get 'by_category/:category', action: :by_category, as: :by_category
      get 'by_quick_search', action: :by_quick_search, as: :by_quick_search
      get 'by_complex_search', action: :by_complex_search, as: :by_complex_search
    end
  end
  resources :upload_files do
    post :create, on: :collection, :defaults => { :format => 'js' }
    get :download_file, on: :member
  end

  namespace :mine do
    resource :profile, controller: :profile
  end
end

app/views/layouts/_footer.html.haml
%nav.navbar.navbar-default.navbar-fixed-bottom{:role => "navigation", :style => "margin-bottom: 0px;"}
  .container
    .container-fluid
      .navbar-header
        %span
          %h4 Copyright Epoch Times 2015

app/views/layouts/_header.html.haml
%nav#header.navbar.navbar-default{:role => "navigation"}
  .container
    .container-fluid
      .navbar-header
        %button.navbar-toggle{"data-target" => ".navbar-collapse", "data-toggle" => "collapse", :type => "button"}
          %span.sr-only Toggle navigation
          %span.icon-bar
          %span.icon-bar
          %span.icon-bar
        %a{"data-no-turbolink" => "true", :href => "/"}
          %h3{:style => "margin-top: 12px;"}= t 'nav.sales_assistant_system'
      #navbar-collapse.collapse.navbar-collapse
        - if current_user
          = form_tag '/posts/by_quick_search', class: "navbar-form navbar-left", id: "nav_search", role: "search", method: :get do
            .form-group
              %input.form-control.col-md-6{:name => "query", :placeholder => "#{t 'nav.search'}", :type => "text"}/
              %button.btn.btn-default{:type => "submit"}= t 'nav.submit'
          %ul.nav.navbar-nav.navbar-right
            %li.dropdown
              %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#", :role => "button"}
                = t('nav.grab_data')
                %span.caret
              %ul.dropdown-menu{:role => "menu"}
                %li{:role => "presentation"}
                  = link_to 'Yelp', yelp_grabs_path

            %li.dropdown{:role => "presentation"}
              %a.dropdown-toggle{"aria-expanded" => "false", "data-toggle" => "dropdown", :href => "#", :role => "button"}
                = t 'nav.boards'
                %span.caret
              %ul.dropdown-menu{:role => "menu"}
                %li= link_to t('board.sales_tools'), sales_tools_path
                %li= link_to t('board.experience_share'), expshare_posts_path
                %li= link_to t('board.activities'), activity_posts_path
                %li= link_to t('board.global_foods'), globalfood_posts_path
                %li= link_to t('board.meeting_records'), meetingrecord_posts_path
                %li= link_to t('board.evaluations'), evaluation_posts_path
            %li.dropdown
              %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#", :role => "button"}
                = current_user.username || current_user.email
                %span.caret
              %ul.dropdown-menu{:role => "menu"}
                %li{:role => "presentation"}
                  = link_to 'Log out', destroy_user_session_path, method: :delete
                  = link_to 'Profile', mine_profile_path
        - else
          %ul.nav.navbar-nav.navbar-right
            %li= link_to t('nav.login'), new_user_session_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title SalesAssistant
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    = render 'layouts/header'
    .container.main-container
      - flash.each do |name, msg|
        = content_tag(:div, msg, class: "alert alert-info")
      = yield
    = render 'layouts/footer'